spring:
  application:
    name: product-service
  config.import: "optional:configserver:"
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://configuration-service:8081
    username: ${CONFIG_SERVER_USR}
    password: ${CONFIG_SERVER_PWD}

---
spring.config.activate.on-profile: docker
spring.cloud.config.uri: http://configuration-service:8081
