spring:
  application:
    name: integration-service
  grpc.client:
    channels:
      inventory.address: inventory-service:8080
      product.address: product-service:8080
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:9092/realms/gateway/protocol/openid-connect/certs"

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

springdoc:
  swagger-ui.path: /product/openapi/swagger-ui.html
  api-docs.path: /product/openapi/v3/api-docs
  packagesToScan: jsl.group.microservices.integration
  pathsToMatch: /**
  cache.disable: true
  swagger-ui:
    oauth2-redirect-uri: /swagger-ui/oauth2-redirect.html
    oauth:
      clientId: openapi-client
      clientSecret: 66zhDyYXxEhKs8RYP8FtlSII5LaTxTak
      useBasicAuthenticationWithAccessCodeGrant: true