spring:
  application:
    name: inventory-service
  grpc.server:
    port: 8080
    host: inventory-service
  datasource:
    url: jdbc:postgresql://postgres/ecommerce
    password: password
    username: username
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
      database: postgresql

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE