spring:
  application:
    name: shipping-service
  cloud:
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        shippingProcessing-in-0:
          destination: shipping
          group: shippingGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          shippingProcessing-in-0:
            autoBindDlq: true
            republishToDlq: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE